# Generated by Django 4.0.4 on 2022-06-04 16:08

import digisafe.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import protocol.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0002_initial'),
        ('centers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countries', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(choices=[('r', 'Attendance register'), ('v', 'Exam reporter'), ('p', 'Privacy'), ('o', 'Other')], default='r', max_length=2)),
                ('file', models.FileField(storage=protocol.models.ProtocolFileSystemStorage(base_url='/document', location='files/'), upload_to=protocol.models.file_path_name, validators=[protocol.models.validate_file_size, protocol.models.validate_file_extension])),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('new', 'New'), ('update', 'Update')], default='new', max_length=25)),
                ('learners_request', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('m', 'Modifica'), ('r', 'Richiesta'), ('c', 'Caricato'), ('a', 'Autorizzato'), ('n', 'Negato'), ('t', 'Terminato'), ('h', 'Chiuso')], default='m', max_length=1)),
                ('warning', models.BooleanField(default=False, editable=False)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.center')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signs',
            fields=[
                ('uiid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pdf_x', models.IntegerField(default=0)),
                ('pdf_y', models.IntegerField(default=0)),
                ('html_x', models.IntegerField(default=0)),
                ('html_y', models.IntegerField(default=0)),
                ('page', models.IntegerField(default=0)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol.files')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=255, null=True)),
                ('subject_type', models.CharField(choices=[('t', 'Theory'), ('p', 'Practice')], default='t', max_length=25)),
                ('execution', models.CharField(choices=[('front', 'In presence'), ('online', 'On the web')], default='front', max_length=25)),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(default='', max_length=255)),
                ('info', models.TextField(default='')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol')),
            ],
        ),
        migrations.CreateModel(
            name='Learners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('inst_cert', models.FileField(blank=True, storage=digisafe.storage.FileInstCertStorage(base_url='/document', location='files/'), upload_to=protocol.models.file_path_name_learner, validators=[protocol.models.validate_file_size, protocol.models.validate_file_extension], verbose_name='Certificate Institution')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name'],
                'unique_together': {('protocol', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='files',
            unique_together={('protocol', 'doc_type')},
        ),
        migrations.CreateModel(
            name='Authorizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(choices=[('a', 'Authorization')], default='a', max_length=2)),
                ('auth_prot', models.CharField(default='', max_length=20)),
                ('file', models.FileField(storage=protocol.models.ProtocolFileSystemStorage(base_url='/document', location='files/'), upload_to=protocol.models.file_path_name, validators=[protocol.models.validate_file_size, protocol.models.validate_file_extension])),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('protocol', 'doc_type')},
            },
        ),
    ]
