# Generated by Django 4.0 on 2021-12-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocol',
            old_name='country',
            new_name='course',
        ),
    ]
