# Generated by Django 4.0 on 2021-12-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0003_alter_session_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.CharField(choices=[('online', 'On the web'), ('front', 'In presence')], default='front', max_length=25),
        ),
    ]
