# Generated by Django 4.0 on 2021-12-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0004_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
