# Generated by Django 4.0 on 2021-12-16 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0006_learners'),
    ]

    operations = [
        migrations.AddField(
            model_name='learners',
            name='protocol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol'),
            preserve_default=False,
        ),
    ]
