# Generated by Django 4.0 on 2021-12-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_profile_administrator'),
        ('protocol', '0008_learners_passed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learners',
            options={'ordering': ['user__last_name']},
        ),
        migrations.AlterUniqueTogether(
            name='learners',
            unique_together={('protocol', 'user')},
        ),
    ]
