# Generated by Django 4.0 on 2021-12-23 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_anagrafica_fiscal_code'),
        ('countries', '0014_alter_country_options'),
        ('protocol', '0012_alter_session_address_alter_session_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='address',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.city'),
        ),
        migrations.AlterField(
            model_name='session',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
