# Generated by Django 4.0 on 2021-12-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0013_alter_session_address_alter_session_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='status',
            field=models.CharField(choices=[('a', 'Richiesta'), ('b', 'Caricato'), ('c', 'Autorizzato'), ('e', 'Rifiutato')], default='a', max_length=1),
        ),
    ]
