# Generated by Django 4.0 on 2021-12-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0015_alter_protocol_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='status',
            field=models.CharField(choices=[('m', 'Modifica'), ('r', 'Richiesta'), ('c', 'Caricato'), ('a', 'Autorizzato'), ('n', 'Negato'), ('t', 'Terminato'), ('h', 'Chiuso')], default='m', max_length=1),
        ),
    ]
