# Generated by Django 4.0 on 2021-12-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0016_alter_protocol_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='type',
            new_name='execution',
        ),
    ]
