# Generated by Django 4.0 on 2021-12-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0017_rename_type_session_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.CharField(choices=[('t', 'Theory'), ('p', 'Practice')], default='t', max_length=25),
        ),
        migrations.AlterField(
            model_name='session',
            name='execution',
            field=models.CharField(choices=[('front', 'In presence'), ('online', 'On the web')], default='front', max_length=25),
        ),
    ]
