# Generated by Django 4.0 on 2021-12-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0018_session_type_alter_session_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='learners_request',
            field=models.IntegerField(default=0),
        ),
    ]
