# Generated by Django 4.0 on 2021-12-31 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
        ('protocol', '0019_protocol_learners_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='centers.center'),
        ),
    ]
