# Generated by Django 4.0 on 2022-01-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0022_message_delete_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
