# Generated by Django 4.0 on 2022-01-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0024_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
