# Generated by Django 4.0 on 2022-01-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('protocol', '0026_protocol_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='institution',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
    ]
