# Generated by Django 4.0 on 2022-01-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_coursesadmitedcenter'),
        ('protocol', '0028_alter_protocol_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.center'),
        ),
    ]
