# Generated by Django 4.0 on 2022-01-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0029_alter_protocol_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('r', 'Attendance register'), ('v', 'Exam reporter')], default='', max_length=2)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol')),
            ],
        ),
    ]
