# Generated by Django 4.0 on 2022-01-06 10:02

from django.db import migrations, models
import protocol.models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0030_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='type',
        ),
        migrations.AddField(
            model_name='files',
            name='doc_type',
            field=models.CharField(choices=[('r', 'Attendance register'), ('v', 'Exam reporter')], default='r', max_length=2),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=protocol.models.file_path_name),
        ),
    ]
