# Generated by Django 4.0 on 2022-01-06 20:46

from django.db import migrations, models
import protocol.models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0032_rename_type_session_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(storage=protocol.models.ProtocolFileSystemStorage(base_url='/document', location='files/'), upload_to=protocol.models.file_path_name, validators=[protocol.models.validate_file_size, protocol.models.validate_file_extension]),
        ),
    ]
