# Generated by Django 4.0 on 2022-01-07 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_institutions'),
        ('protocol', '0035_files_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
