# Generated by Django 4.0 on 2022-01-07 10:20

from django.db import migrations, models
import django.db.models.deletion
import protocol.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_institutions'),
        ('protocol', '0036_alter_files_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(choices=[('a', 'Authorization'), ('o', 'Other informations')], default='a', max_length=2)),
                ('file', models.FileField(storage=protocol.models.ProtocolFileSystemStorage(base_url='/document', location='files/'), upload_to=protocol.models.file_path_name, validators=[protocol.models.validate_file_size, protocol.models.validate_file_extension])),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('protocol', 'doc_type')},
            },
        ),
    ]
