# Generated by Django 4.0 on 2022-01-10 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0037_authorizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
