# Generated by Django 4.0 on 2022-01-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0040_signs_file_pag_signs_html_x_signs_html_y_signs_pdf_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signs',
            name='file_pag',
        ),
        migrations.AddField(
            model_name='signs',
            name='page',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signs',
            name='html_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='signs',
            name='html_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='signs',
            name='pdf_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='signs',
            name='pdf_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
