# Generated by Django 4.0 on 2022-01-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0041_remove_signs_file_pag_signs_page_alter_signs_html_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signs',
            name='html_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signs',
            name='html_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signs',
            name='pdf_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signs',
            name='pdf_y',
            field=models.IntegerField(default=0),
        ),
    ]
