# Generated by Django 4.0 on 2022-01-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0042_alter_signs_html_x_alter_signs_html_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='signs',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
