# Generated by Django 4.0 on 2022-01-21 19:04

from django.db import migrations, models
import protocol.models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0043_protocol_warning_alter_signs_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='learners',
            name='inst_cert',
            field=models.FileField(blank=True, storage=protocol.models.ProtocolFileSystemStorage(base_url='/document', location='files/'), upload_to=protocol.models.file_path_name, validators=[protocol.models.validate_file_size, protocol.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='warning',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
