# Generated by Django 4.0 on 2022-01-23 12:18

import django.core.files.storage
from django.db import migrations, models
import protocol.models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0044_learners_inst_cert_alter_protocol_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learners',
            name='inst_cert',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/document', location='files/'), upload_to=protocol.models.file_path_name_learner, validators=[protocol.models.validate_file_size, protocol.models.validate_file_extension], verbose_name='Certificate Institution'),
        ),
    ]
