# Generated by Django 4.0 on 2022-01-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0045_alter_learners_inst_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizations',
            name='doc_type',
            field=models.CharField(choices=[('a', 'Authorization')], default='a', max_length=2),
        ),
        migrations.AlterField(
            model_name='authorizations',
            name='protocol',
            field=models.CharField(default='', max_length=20),
        ),
    ]
