# Generated by Django 4.0 on 2022-01-23 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0046_alter_authorizations_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizations',
            name='auth_prot',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='authorizations',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol.protocol'),
        ),
    ]
