# Generated by Django 4.0.1 on 2022-02-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0047_authorizations_auth_prot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='doc_type',
            field=models.CharField(choices=[('r', 'Attendance register'), ('v', 'Exam reporter'), ('p', 'Privacy'), ('o', 'Other')], default='r', max_length=2),
        ),
    ]
