# Generated by Django 4.0.1 on 2022-02-20 10:44

import digisafe.storage
from django.db import migrations, models
import protocol.models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0048_alter_files_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learners',
            name='inst_cert',
            field=models.FileField(blank=True, storage=digisafe.storage.FileInstCertStorage(base_url='/document', location='files/'), upload_to=protocol.models.file_path_name_learner, validators=[protocol.models.validate_file_size, protocol.models.validate_file_extension], verbose_name='Certificate Institution'),
        ),
    ]
