# Generated by Django 4.0.4 on 2022-06-04 16:08

import courses.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i18', models.CharField(default='', max_length=5)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('need_institution', models.BooleanField(default=False)),
                ('country', models.ManyToManyField(blank=True, help_text='Stati permessi', to='countries.country')),
            ],
            options={
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('theory', courses.models.DurationField(default=0)),
                ('practice', courses.models.DurationField(default=0)),
                ('max_learners_theory', models.IntegerField(default=0, help_text='Per course')),
                ('max_learners_practice', models.IntegerField(default=0, help_text='Per trainer')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
            options={
                'verbose_name_plural': 'Update',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', courses.models.DurationField(default=0)),
                ('practice', courses.models.DurationField(default=0)),
                ('max_learners_theory', models.IntegerField(default=0, help_text='Per course')),
                ('max_learners_practice', models.IntegerField(default=0, help_text='Per trainer')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
            options={
                'verbose_name_plural': 'New',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('desc', models.TextField(blank=True, default='')),
                ('laws', models.TextField(blank=True, default='')),
                ('years', models.IntegerField(blank=True, default=5)),
                ('notes', models.TextField(blank=True, default='')),
                ('risk', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'Higth')], default='L', max_length=1)),
                ('contents', models.ManyToManyField(blank=True, to='courses.contentcourse')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
            options={
                'verbose_name_plural': 'features',
            },
        ),
        migrations.AddField(
            model_name='contentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
        migrations.AlterUniqueTogether(
            name='contentcourse',
            unique_together={('course', 'i18')},
        ),
    ]
