# Generated by Django 4.0 on 2021-12-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_course_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='laws',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='feature',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feature',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
