# Generated by Django 4.0 on 2021-12-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_feature_laws_feature_notes_feature_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='new',
            name='practice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='new',
            name='theory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='update',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='update',
            name='practice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='update',
            name='theory',
            field=models.IntegerField(default=0),
        ),
    ]
