# Generated by Django 4.0 on 2021-12-13 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_new_hours_new_practice_new_theory_update_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='new',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='update',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
    ]
