# Generated by Django 4.0 on 2021-12-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_feature_course_alter_new_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
