# Generated by Django 4.0 on 2021-12-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_feature_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feature',
            name='laws',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feature',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
