# Generated by Django 4.0 on 2021-12-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_feature_desc_alter_feature_laws_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='name',
        ),
    ]
