# Generated by Django 4.0 on 2021-12-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0013_rename_catasto_city_sigla_prov_city_prov'),
        ('courses', '0008_remove_courses_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='country',
            field=models.ManyToManyField(blank=True, help_text='Stati permessi', to='countries.Country'),
        ),
    ]
