# Generated by Django 4.0 on 2021-12-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courses_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='new',
            name='year',
        ),
        migrations.RemoveField(
            model_name='update',
            name='hours',
        ),
    ]
