# Generated by Django 4.0 on 2021-12-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_new_hours_remove_new_year_remove_update_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
