# Generated by Django 4.0 on 2021-12-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_new_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='practice',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='update',
            name='theory',
            field=models.DurationField(default=0),
        ),
    ]
