# Generated by Django 4.0 on 2021-12-30 10:53

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_update_practice_alter_update_theory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='max_learners_practice',
            field=models.IntegerField(default=0, help_text='Per trainer'),
        ),
        migrations.AlterField(
            model_name='new',
            name='max_learners_theory',
            field=models.IntegerField(default=0, help_text='Per course'),
        ),
        migrations.AlterField(
            model_name='new',
            name='practice',
            field=courses.models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='new',
            name='theory',
            field=courses.models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='update',
            name='max_learners_practice',
            field=models.IntegerField(default=0, help_text='Per trainer'),
        ),
        migrations.AlterField(
            model_name='update',
            name='max_learners_theory',
            field=models.IntegerField(default=0, help_text='Per course'),
        ),
        migrations.AlterField(
            model_name='update',
            name='practice',
            field=courses.models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='update',
            name='theory',
            field=courses.models.DurationField(default=0),
        ),
    ]
