# Generated by Django 4.0 on 2022-01-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_new_max_learners_practice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='need_institution',
            field=models.BooleanField(default=False),
        ),
    ]
