# Generated by Django 4.0 on 2022-01-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_courses_need_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='risk',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'Higth')], default='L', max_length=1),
        ),
    ]
