# Generated by Django 4.0 on 2022-01-23 12:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_feature_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='content',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
