# Generated by Django 4.0 on 2022-01-23 12:25

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_feature_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='content',
        ),
        migrations.CreateModel(
            name='ContentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i18', models.CharField(default='', max_length=4)),
                ('content', tinymce.models.HTMLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.feature')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='contents',
            field=models.ManyToManyField(blank=True, to='courses.ContentCourse'),
        ),
    ]
