# Generated by Django 4.0 on 2022-01-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_feature_content_contentcourse_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentcourse',
            unique_together={('course', 'i18')},
        ),
    ]
