# Generated by Django 4.0 on 2022-01-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_contentcourse_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcourse',
            name='i18',
            field=models.CharField(default='', max_length=5),
        ),
    ]
