# Generated by Django 4.0 on 2022-01-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_contentcourse_i18'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='years',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
