# Generated by Django 4.0 on 2022-01-23 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_feature_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
    ]
