# Generated by Django 4.0.4 on 2022-06-04 16:08

import centers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('logo', models.FileField(blank=True, storage=centers.models.ProtocolFileSystemStorage(base_url='/imgs', location='static/imgs/'), upload_to=centers.models.file_path_name_center, validators=[centers.models.validate_file_size, centers.models.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='CoursesAdmitedCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='centers.center')),
                ('courses', models.ManyToManyField(blank=True, help_text='Corsi gestiti', to='courses.courses')),
            ],
        ),
    ]
