# Generated by Django 4.0.4 on 2022-06-04 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='center',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='associate_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='center',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='associate_centers', to=settings.AUTH_USER_MODEL),
        ),
    ]
