# Generated by Django 4.0 on 2022-01-09 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_institutions'),
        ('centers', '0002_coursesadmitedcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='director',
            field=models.ForeignKey(default=162, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
