# Generated by Django 4.0 on 2022-01-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_institutions'),
        ('centers', '0003_center_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
