# Generated by Django 4.0 on 2022-01-10 11:35

import centers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_alter_center_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='logo',
            field=models.FileField(blank=True, storage=centers.models.ProtocolFileSystemStorage(base_url='/imgs', location='imgs/'), upload_to=centers.models.file_path_name_center, validators=[centers.models.validate_file_size, centers.models.validate_file_extension]),
        ),
    ]
