# Generated by Django 4.0 on 2022-01-11 18:51

import centers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_center_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='logo',
            field=models.FileField(blank=True, storage=centers.models.ProtocolFileSystemStorage(base_url='/imgs', location='static/imgs/'), upload_to=centers.models.file_path_name_center, validators=[centers.models.validate_file_size, centers.models.validate_file_extension]),
        ),
    ]
