# Generated by Django 4.0.1 on 2022-02-20 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centers', '0006_alter_center_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='associate_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
