# Generated by Django 4.0.1 on 2022-02-20 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centers', '0008_remove_center_users_center_trainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='associate_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
