# Generated by Django 4.0.1 on 2022-02-20 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centers', '0009_center_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='associate_centers', to=settings.AUTH_USER_MODEL),
        ),
    ]
