# Generated by Django 4.0.1 on 2022-01-30 18:57

from django.db import migrations, models
import django.utils.timezone
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='imestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='position',
            name='pos',
            field=djgeojson.fields.PointField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
