# Generated by Django 4.0.1 on 2022-01-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_position_imestamp_position_pos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='imestamp',
            new_name='timestamp',
        ),
    ]
