# Generated by Django 4.0.1 on 2022-01-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_imestamp_position_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='pos',
            new_name='geom',
        ),
    ]
