# Generated by Django 4.0.1 on 2022-01-30 19:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_rename_pos_position_geom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='position',
            new_name='UsersPosition',
        ),
    ]
