# Generated by Django 4.0.1 on 2022-03-14 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_position_usersposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersposition',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersposition',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersposition',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
