# Generated by Django 4.0.1 on 2022-03-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_usersposition_date_end_usersposition_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersposition',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
