# Generated by Django 4.0.1 on 2022-03-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_usersposition_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersposition',
            old_name='busy',
            new_name='anonymous',
        ),
        migrations.AddField(
            model_name='usersposition',
            name='object',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersposition',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
