# Generated by Django 4.0.1 on 2022-04-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_agenda_anonymous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='geom',
            new_name='city',
        ),
    ]
