# Generated by Django 4.0.1 on 2022-04-16 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0013_rename_geom_agenda_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Agendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('object', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
