# Generated by Django 4.0.1 on 2022-04-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_rename_agenda2_cancellare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cancellare',
        ),
    ]
