# Generated by Django 4.0.1 on 2022-04-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_rename_diario_agenda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agenda2',
        ),
    ]
