# Generated by Django 4.0.1 on 2022-04-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_delete_agenda2'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='busy',
            field=models.BooleanField(default=True),
        ),
    ]
