# Generated by Django 4.0.1 on 2022-04-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_agenda_busy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agenda',
        ),
    ]
