# Generated by Django 4.0.4 on 2022-05-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0009_pricelist_note'),
        ('account', '0024_sessionprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionprice',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricelist.pricelist'),
        ),
    ]
