# Generated by Django 4.0.4 on 2022-05-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_sessionprice_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionPrice',
        ),
    ]
