# Generated by Django 4.0 on 2022-01-27 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('admins', models.ManyToManyField(blank=True, related_name='admins_company', to=settings.AUTH_USER_MODEL)),
                ('associates', models.ManyToManyField(blank=True, related_name='associates_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
