# Generated by Django 4.0 on 2022-01-27 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_profile_sign'),
        ('companies', '0002_company_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestAssociatePending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ok', models.BooleanField(default=False)),
                ('company_ok', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
