# Generated by Django 4.0 on 2022-01-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_requestassociatepending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestassociatepending',
            old_name='company_ok',
            new_name='company_req',
        ),
        migrations.RenameField(
            model_name='requestassociatepending',
            old_name='user_ok',
            new_name='user_req',
        ),
    ]
