# Generated by Django 4.0.1 on 2022-02-17 17:35

import digisafe.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_profile_city_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.FileField(default='', storage=digisafe.storage.FileSystemStorage(base_url='/imgs', location='static/imgs/'), upload_to=digisafe.storage.file_path_name_center, validators=[digisafe.storage.validate_file_size, digisafe.storage.validate_file_extension_img]),
            preserve_default=False,
        ),
    ]
