# Generated by Django 4.0.1 on 2022-02-18 08:32

import companies.models
import digisafe.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_profile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.FileField(storage=digisafe.storage.FileSystemStorage(base_url='/imgs', location='static/imgs/'), upload_to=companies.models.file_path_name_company, validators=[digisafe.storage.validate_file_size, digisafe.storage.validate_file_extension_img]),
        ),
    ]
