# Generated by Django 4.0.1 on 2022-04-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_favoriteuser_delete_marker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteUser',
        ),
    ]
