# Generated by Django 4.0.1 on 2022-04-18 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0011_delete_favoriteuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
