# Generated by Django 4.0.1 on 2022-04-26 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0013_sessionbook_userbook_datebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='datebook',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserBook',
        ),
    ]
