# Generated by Django 4.0.1 on 2022-04-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_sessionbook_end_date_sessionbook_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datebook',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='datebook',
            name='time_start',
        ),
    ]
