# Generated by Django 4.0.1 on 2022-04-26 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0016_remove_datebook_time_end_remove_datebook_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbook',
            name='user_option_list',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
