# Generated by Django 4.0.1 on 2022-04-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_sessionbook_user_option_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbook',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
