# Generated by Django 4.0.1 on 2022-04-28 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_sessionbook_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbook',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
