# Generated by Django 4.0.4 on 2022-05-04 03:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_title'),
        ('companies', '0020_alter_datebook_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='datebook',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datebook',
            name='number_user',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
