# Generated by Django 4.0.4 on 2022-05-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_title'),
        ('companies', '0021_datebook_job_datebook_number_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbook',
            name='jobs',
            field=models.ManyToManyField(to='job.job'),
        ),
    ]
