# Generated by Django 4.0.4 on 2022-05-04 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_title'),
        ('companies', '0022_sessionbook_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebook',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_datebook', to='job.job'),
        ),
    ]
