# Generated by Django 4.0.4 on 2022-05-06 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0027_alter_sessionbook_user_decline_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datebook',
            name='users_confirm',
            field=models.ManyToManyField(blank=True, related_name='datebook_confirm', to=settings.AUTH_USER_MODEL),
        ),
    ]
