# Generated by Django 4.0.4 on 2022-05-08 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_datebook_users_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebook',
            name='number_user',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
