# Generated by Django 4.0.4 on 2022-05-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_alter_datebook_number_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datebook',
            name='company_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='datebook',
            name='user_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
