# Generated by Django 4.0.4 on 2022-05-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0030_datebook_company_note_datebook_user_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionbook',
            name='address',
        ),
    ]
