# Generated by Django 4.0.4 on 2022-05-14 05:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_remove_sessionbook_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbook',
            name='city',
            field=django.contrib.gis.db.models.fields.PointField(default=[], srid=4326),
            preserve_default=False,
        ),
    ]
