# Generated by Django 4.0.4 on 2022-05-14 08:18

from django.db import migrations, models
import maps.gisfields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_sessionbook_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbook',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
