# Generated by Django 4.0.4 on 2022-05-14 09:30

from django.db import migrations, models
import maps.gisfields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0033_alter_sessionbook_city_alter_sessionbook_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebook',
            name='user_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
