# Generated by Django 4.0.4 on 2022-05-16 17:20

from django.db import migrations, models
import django.db.models.deletion
import maps.gisfields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_alter_datebook_user_note_alter_sessionbook_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebook',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datebook_set', to='companies.sessionbook'),
        ),
    ]
