# Generated by Django 4.0.4 on 2022-06-01 06:43

from django.db import migrations, models
import django.db.models.deletion
import maps.gisfields


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0014_alter_country_options'),
        ('companies', '0035_alter_datebook_session_alter_sessionbook_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.city', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.TextField(default='', verbose_name='description'),
        ),
    ]
