# Generated by Django 4.0.1 on 2022-04-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
