# Generated by Django 4.0.1 on 2022-04-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
    ]
