# Generated by Django 4.0.1 on 2022-04-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='code',
        ),
    ]
