# Generated by Django 4.0.1 on 2022-04-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='code',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
