# Generated by Django 4.0.1 on 2022-04-15 10:23

from django.db import migrations
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='code',
            field=job.models.UpperCaseCharField(default='', max_length=50, unique=True),
        ),
    ]
