# Generated by Django 4.0.1 on 2022-04-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
