# Generated by Django 4.0.1 on 2022-04-21 04:37

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('city', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('busy', models.BooleanField(default=True)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('object', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
