# Generated by Django 4.0.1 on 2022-04-21 04:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0002_agendaproperty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgendaProperty',
            new_name='AgendaFeatures',
        ),
    ]
