# Generated by Django 4.0.4 on 2022-05-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0030_datebook_company_note_datebook_user_note'),
        ('agenda', '0003_rename_agendaproperty_agendafeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='datebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.datebook'),
        ),
    ]
