# Generated by Django 4.0.4 on 2022-06-04 16:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import institutions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesAdmitedInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('logo', models.FileField(blank=True, storage=institutions.models.InstitutionFileSystemStorage(base_url='/imgs', location='static/imgs/'), upload_to=institutions.models.file_path_name_institution, validators=[institutions.models.validate_file_size, institutions.models.validate_file_extension])),
                ('use_custom_files', models.BooleanField(default=False, verbose_name='Use custom registry files')),
                ('pre_days', models.IntegerField(default=0, help_text='Days before insert request', validators=[django.core.validators.MinValueValidator(0, 'Min values is 0')])),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionCustomFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('file', models.FileField(storage=institutions.models.InstitutionFileSystemStorage(base_url='/document', location='files/'), upload_to=institutions.models.customfile_path_name_institution, validators=[institutions.models.validate_file_size, institutions.models.validate_customfile_extension])),
                ('need', models.BooleanField(default=False, help_text='Check that if this file is mandatory')),
                ('description', models.TextField(blank=True, default='')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
        ),
    ]
