# Generated by Django 4.0.4 on 2022-06-04 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0002_initial'),
        ('institutions', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institution',
            name='centers',
            field=models.ManyToManyField(blank=True, related_name='associate_institutions', to='centers.center'),
        ),
        migrations.AddField(
            model_name='institution',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='institution_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursesadmitedinstitution',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Corsi gestiti', to='courses.courses'),
        ),
        migrations.AddField(
            model_name='coursesadmitedinstitution',
            name='institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
    ]
