# Generated by Django 4.0.1 on 2022-02-06 08:58

from django.db import migrations, models
import django.db.models.deletion
import institutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_coursesadmitedinstitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.FileField(blank=True, storage=institutions.models.InstitutionFileSystemStorage(base_url='/imgs', location='static/imgs/'), upload_to=institutions.models.file_path_name_institution, validators=[institutions.models.validate_file_size, institutions.models.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='institution',
            name='use_custom_files',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='institutioCustomFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(blank=True, storage=institutions.models.InstitutionFileSystemStorage(base_url='/imgs', location='static/imgs/'), upload_to=institutions.models.file_path_name_institution, validators=[institutions.models.validate_file_size, institutions.models.validate_customfile_extension])),
                ('need', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
        ),
    ]
