# Generated by Django 4.0.1 on 2022-02-06 10:21

from django.db import migrations, models
import institutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_institution_logo_institution_use_custom_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutiocustomfiles',
            name='file',
            field=models.FileField(storage=institutions.models.InstitutionFileSystemStorage(base_url='/document', location='files/'), upload_to=institutions.models.customfile_path_name_institution, validators=[institutions.models.validate_file_size, institutions.models.validate_customfile_extension]),
        ),
        migrations.AlterField(
            model_name='institutiocustomfiles',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
