# Generated by Django 4.0.1 on 2022-02-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_alter_institutiocustomfiles_file_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='institutioCustomFiles',
            new_name='InstitutionCustomFiles',
        ),
    ]
