# Generated by Django 4.0.1 on 2022-02-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_rename_institutiocustomfiles_institutioncustomfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='use_custom_files',
            field=models.BooleanField(default=False, verbose_name='Use custom registry files'),
        ),
        migrations.AlterField(
            model_name='institutioncustomfiles',
            name='need',
            field=models.BooleanField(default=False, help_text='Check that if this file is mandatory'),
        ),
    ]
