# Generated by Django 4.0.1 on 2022-02-20 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centers', '0010_alter_center_trainers'),
        ('institutions', '0008_alter_institution_use_custom_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institution',
            name='centers',
            field=models.ManyToManyField(blank=True, related_name='associate_institutions', to='centers.Center'),
        ),
    ]
