# Generated by Django 4.0.1 on 2022-03-02 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0009_institution_admin_institution_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='institution_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
