# Generated by Django 4.0.1 on 2022-03-08 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_institution_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='pre_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Min values is 0')]),
        ),
    ]
