# Generated by Django 4.0.1 on 2022-03-14 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_institution_pre_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='pre_days',
            field=models.IntegerField(default=0, help_text='Days before insert request', validators=[django.core.validators.MinValueValidator(0, 'Min values is 0')]),
        ),
    ]
