# Generated by Django 3.2.7 on 2021-12-08 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_anagrafica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagrafica',
            name='author',
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
