# Generated by Django 3.2.7 on 2021-12-08 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211208_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagrafica',
            name='data_nascita',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
