# Generated by Django 3.2.7 on 2021-12-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_anagrafica_data_nascita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='data_nascita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
