# Generated by Django 4.0 on 2021-12-08 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0008_city_catasto'),
        ('users', '0006_alter_anagrafica_data_nascita'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagrafica',
            name='citta_nascita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.city'),
        ),
    ]
