# Generated by Django 4.0 on 2021-12-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0008_city_catasto'),
        ('users', '0007_anagrafica_citta_nascita'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagrafica',
            name='provincia_nascita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.province'),
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='regione_nascita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.state'),
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='stato_nascita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
        ),
    ]
