# Generated by Django 4.0 on 2021-12-13 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_course_courses'),
        ('users', '0012_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
    ]
