# Generated by Django 4.0 on 2021-12-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_new_hours_new_practice_new_theory_update_hours_and_more'),
        ('users', '0013_subjects_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjects',
            unique_together={('user', 'course')},
        ),
    ]
