# Generated by Django 4.0 on 2021-12-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_courses_name'),
        ('users', '0016_alter_subjects_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='courses.Courses'),
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
