# Generated by Django 4.0 on 2021-12-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_subjects_delete_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
