# Generated by Django 4.0 on 2021-12-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_courses_name'),
        ('users', '0021_alter_subjects_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='course',
        ),
        migrations.AddField(
            model_name='subjects',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.Courses'),
        ),
    ]
