# Generated by Django 4.0 on 2021-12-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_subjects_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subjects',
        ),
    ]
