# Generated by Django 4.0 on 2021-12-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_courses_name'),
        ('users', '0025_alter_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='courses',
        ),
        migrations.AddField(
            model_name='subjects',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Corsi permessi', to='courses.Courses'),
        ),
    ]
