# Generated by Django 4.0 on 2021-12-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_subjects_courses_subjects_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
