# Generated by Django 4.0 on 2021-12-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_rename_privilegi_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='direttore',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='docente',
            new_name='trainer',
        ),
    ]
