# Generated by Django 4.0 on 2021-12-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_rename_direttore_profile_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagrafica',
            name='fiscal_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
