# Generated by Django 4.0 on 2021-12-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_anagrafica_fiscal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='administrator',
            field=models.BooleanField(default=False),
        ),
    ]
