# Generated by Django 4.0 on 2021-12-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_user_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='fiscal_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
