# Generated by Django 4.0 on 2021-12-31 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
        ('users', '0036_profile_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('centers', models.ManyToManyField(blank=True, help_text='Centri associati', to='centers.Center')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
