# Generated by Django 4.0 on 2022-01-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_trainingcenter'),
    ]

    operations = [
    ]
