# Generated by Django 4.0 on 2022-01-17 09:50

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_institutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sign',
            field=models.FileField(default='', storage=users.models.ProtocolFileSystemStorage(base_url='/signs', location='signs/'), upload_to=users.models.file_path_name, validators=[users.models.validate_file_size, users.models.validate_file_extension]),
            preserve_default=False,
        ),
    ]
