# Generated by Django 4.0 on 2022-01-27 08:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_subjects_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sign',
            field=models.ImageField(blank=True, storage=users.models.ProtocolFileSystemStorage(base_url='/signs', location='signs/'), upload_to=users.models.file_path_name, validators=[users.models.validate_file_size, users.models.validate_file_extension, users.models.validate_file_trasparence]),
        ),
    ]
