# Generated by Django 4.0.1 on 2022-02-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_profile_sign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingCenter',
        ),
    ]
