# Generated by Django 4.0.1 on 2022-04-20 14:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_jobprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='home_position',
            field=django.contrib.gis.db.models.fields.PointField(default=[0, 0], srid=4326),
        ),
    ]
