# Generated by Django 4.0.1 on 2022-04-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_jobprofile_home_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprofile',
            name='home_position',
        ),
    ]
