# Generated by Django 4.0.1 on 2022-04-20 14:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_remove_jobprofile_home_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='home_position',
            field=django.contrib.gis.db.models.fields.PointField(default=(0.0, 0.0), srid=4326),
            preserve_default=False,
        ),
    ]
