# Generated by Django 4.0.4 on 2022-06-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('code', models.CharField(default='', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('prov', models.CharField(default='', max_length=255)),
                ('sigla_prov', models.CharField(default='', max_length=10)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
