# Generated by Django 4.0 on 2021-12-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20211208_1136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citie',
            new_name='City',
        ),
    ]
