# Generated by Django 4.0 on 2021-12-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_countrie_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countrie',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='countrie',
            new_name='country',
        ),
    ]
