# Generated by Django 4.0 on 2021-12-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_rename_countrie_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
