# Generated by Django 4.0 on 2021-12-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_province_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='catasto',
            field=models.CharField(default='', max_length=10),
        ),
    ]
