# Generated by Django 4.0 on 2021-12-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0008_city_catasto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
    ]
