# Generated by Django 4.0 on 2021-12-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0010_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
    ]
