# Generated by Django 4.0 on 2021-12-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0011_remove_city_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
