# Generated by Django 4.0 on 2021-12-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0012_remove_state_country_delete_province_delete_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='catasto',
            new_name='sigla_prov',
        ),
        migrations.AddField(
            model_name='city',
            name='prov',
            field=models.CharField(default='', max_length=255),
        ),
    ]
