# Generated by Django 4.0 on 2021-12-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0013_rename_catasto_city_sigla_prov_city_prov'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'countries'},
        ),
    ]
