# Generated by Django 4.0.4 on 2022-05-09 09:03

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0002_pricelist_price_day_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='price_day_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='price_hour_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='price_session_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
    ]
