# Generated by Django 4.0.4 on 2022-05-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0003_alter_pricelist_price_day_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricelist',
            old_name='price_day',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='pricelist',
            old_name='price_day_currency',
            new_name='price_currency',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='price_hour',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='price_hour_currency',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='price_session',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='price_session_currency',
        ),
    ]
