# Generated by Django 4.0.4 on 2022-05-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0004_rename_price_day_pricelist_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='slot_time',
            field=models.CharField(choices=[('HOUR', 'every Hour'), ('DAY', 'every Day'), ('SESSION', 'every Session')], default='HOUR', max_length=8),
        ),
    ]
