# Generated by Django 4.0.4 on 2022-05-17 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0005_pricelist_slot_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('qta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(choices=[('PERC', '%'), ('MONEY', 'Money')], default='PERC', max_length=8)),
                ('add_minus', models.CharField(choices=[('add', 'Add'), ('minus', 'Minus'), ('incluse', 'Incluse')], default='add', max_length=8)),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricelist.pricelist')),
            ],
        ),
    ]
