# Generated by Django 4.0.4 on 2022-05-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0006_extralist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtraList',
            new_name='ExtraPriceList',
        ),
    ]
