# Generated by Django 4.0.4 on 2022-05-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0008_alter_extrapricelist_qta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
