# Generated by Django 4.0.4 on 2022-05-23 03:58

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0010_sessionprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionprice',
            name='price_metadata',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='extrapricelist',
            name='add_minus',
            field=models.CharField(choices=[('add', '+'), ('minus', '-'), ('incluse', 'Incluse')], default='add', max_length=8),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=7, validators=[djmoney.models.validators.MinMoneyValidator(0), djmoney.models.validators.MaxMoneyValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
    ]
